name: roundabout-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - polars
  - pandas
  - matplotlib
  - pyarrow
  - numpy
  - pip:
      - beautifulsoup4
      - selenium
      - requests
      - webdriver-manager
      - lxml
      - statsmodels
      - seaborn
      - mediapy